### ISSUE TITLE
Mac OS X 10.9에서 단디 오류/해결 

### ISSUE THREAD

**Issue by atlkitol** [fallroot/dandy#1]
Mac OS X 10.9 Mavericks (현재시점으로 차기버전) 하에서 단디가 스크립트 오류가 납니다.
- OS 버전: Mac OS X 10.9 OS X Build 13A598
- built-in Ruby 버전 : ruby 2.0.0p247 (2013-06-27 revision 41674

원인 : 문자열 교체과정 중 인코딩이 맞지않으면 실행되지 않고 오류가 발생한다.
~/.dandy/run.rb의 42번째 줄 : 
template.gsub! '{{source}}', source
=> ASCII에서 UTF-8로 교체 불가능하다는 에러 발생

해결 : 명시적으로 인코딩 강제변환을 한다.
~/.dandy/run.rb의 42번째 줄 이전에 다음코드 2줄을 삽입한다.
source.force_encoding("UTF-8")
template.force_encoding("UTF-8")

임시방편으로 고쳐 사용중입니다. 
개인컴퓨터 1대라서 기타 다른 환경에서는 적용시켜보지 못했습니다.
이 방법이라든지 다른 깔끔한 방법이 있으시면 10.9 정식출시에 반영 부탁드립니다.

**Comment by EBvi** [comment]
제 경우엔 루비를 실행시킬 때에도 옵션을 더 줘야 제대로 실행이 되었습니다.

**dandy.workflow**를 automator로 연 후에 다음 소스 코드를 변경해주었습니다.

#### before:

> do shell script "ruby ~/.dandy/run.rb"

#### after:

> do shell script "ruby -E UTF-8 ~/.dandy/run.rb"

참고 부탁드립니다

**Comment by fallroot** [comment]
넵 감사합니다.

같은 절차로 저도 `force_encoding`만으로 해결이 되는 줄 알았다가 `ruby -E utf-8` 옵션까지 사용하고야 말았네요.
개발 브랜치에 반영했습니다.
