### ISSUE TITLE
\` 특수문자 오류

### ISSUE THREAD

**Issue by outsideris** [fallroot/dandy#2]
> <pre>* **multistr**: `\`를 사용해서 문자열을 여러 라인에 걸쳐서 사용하는 경우 발생하는 오류를 보여주지 않는다.</pre>

위와 같은 문장에서  \`  부분때문에 AppleScript 실행동작에 오류가 발생했다는 오류가 나옵니다.

**Comment by fallroot** [comment]
https://github.com/fallroot/dandy/commit/313288c3a98c5b1001ee9f96ace549609c8ee744

말씀대로 백슬래시가 정규식에서 이스케이프 문자로 처리되서 그렇군요.

**Comment by outsideris** [comment]
:+1:
